# Linear Regression using PyTorch

In [1]:
import torch
import numpy as np

In [2]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.rand(2, requires_grad=True)
w, b

(tensor([[-1.4290, -0.7688,  0.1079],
         [-0.5987,  0.1824,  0.2630]], requires_grad=True),
 tensor([0.1492, 0.8500], requires_grad=True))

In [6]:
def model(x):
    #x@w.t() +b == X x WT + b
    return x@w.t() + b

In [7]:
preds = model(inputs)
print(preds)

tensor([[-151.0307,  -19.3205],
        [-190.6294,  -20.7423],
        [-220.9248,  -11.5348],
        [-174.6674,  -42.6374],
        [-164.6950,   -4.5345]], grad_fn=<AddBackward0>)


In [8]:
diff = preds - targets

In [9]:
print(targets)
print(diff)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
tensor([[-207.0307,  -89.3205],
        [-271.6294, -121.7423],
        [-339.9248, -144.5348],
        [-196.6674,  -79.6374],
        [-267.6950, -123.5345]], grad_fn=<SubBackward0>)


In [10]:
#loss
def mse(t1, t2):
    diff = (t1-t2)
    return torch.sum((diff*diff)) / diff.numel()

In [11]:
loss = mse(preds, targets)
print(loss)

tensor(40782.4297, grad_fn=<DivBackward0>)


In [12]:
loss.backward()

In [13]:
w.grad, b.grad

(tensor([[-21587.1992, -23495.9551, -14403.5156],
         [ -9364.0723, -10269.8340,  -6321.8599]]),
 tensor([-256.5895, -111.7539]))

In [14]:
#reset grads to 0
w.grad.zero_()
b.grad.zero_()

tensor([0., 0.])

In [15]:
#function to train for multiple epoch
for i in range(200):
    #1. make predictions
    preds = model(inputs)
        
    #2. calculate loss
    loss = mse(preds, targets)
        
    #3. compute gradients w.r.t weights and biases
    loss.backward()
        
    #4. adjust gradients by small quantity and reset gradients to 0
    with torch.no_grad():
        w -= 1e-5*w.grad
        b -= 1e-5*b.grad
        w.grad.zero_()
        b.grad.zero_()
    if ((i+1)%10 == 0):
        print("Loss at {}th Epoch {}", i+1, loss)

Loss at {}th Epoch {} 10 tensor(1220.7020, grad_fn=<DivBackward0>)
Loss at {}th Epoch {} 20 tensor(70.5608, grad_fn=<DivBackward0>)
Loss at {}th Epoch {} 30 tensor(43.5473, grad_fn=<DivBackward0>)
Loss at {}th Epoch {} 40 tensor(38.7844, grad_fn=<DivBackward0>)
Loss at {}th Epoch {} 50 tensor(34.9439, grad_fn=<DivBackward0>)
Loss at {}th Epoch {} 60 tensor(31.5552, grad_fn=<DivBackward0>)
Loss at {}th Epoch {} 70 tensor(28.5578, grad_fn=<DivBackward0>)
Loss at {}th Epoch {} 80 tensor(25.9050, grad_fn=<DivBackward0>)
Loss at {}th Epoch {} 90 tensor(23.5561, grad_fn=<DivBackward0>)
Loss at {}th Epoch {} 100 tensor(21.4749, grad_fn=<DivBackward0>)
Loss at {}th Epoch {} 110 tensor(19.6297, grad_fn=<DivBackward0>)
Loss at {}th Epoch {} 120 tensor(17.9926, grad_fn=<DivBackward0>)
Loss at {}th Epoch {} 130 tensor(16.5390, grad_fn=<DivBackward0>)
Loss at {}th Epoch {} 140 tensor(15.2473, grad_fn=<DivBackward0>)
Loss at {}th Epoch {} 150 tensor(14.0982, grad_fn=<DivBackward0>)
Loss at {}th Epoc

In [16]:
print(preds, '\n',targets)

tensor([[ 57.7335,  71.1697],
        [ 84.3224,  99.2737],
        [112.9687, 134.7536],
        [ 24.4020,  40.9864],
        [103.6948, 114.5597]], grad_fn=<AddBackward0>) 
 tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


# Linear Regression using PyTorch built-ins

In [17]:
import torch.nn as nn

In [18]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [19]:
inputs.shape

torch.Size([15, 3])

In [20]:
targets.shape

torch.Size([15, 2])

In [21]:
from torch.utils.data import TensorDataset

In [22]:
#Define dataset
train_ds = TensorDataset(inputs, targets)

In [23]:
train_ds[:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [24]:
#dataloader: enables split data into batches, shuffle, random sampling, etc
from torch.utils.data import DataLoader

In [25]:
#define dataloader
batch_size = 5
train_dl = DataLoader(dataset=train_ds, batch_size=batch_size, shuffle=True)

In [26]:
for xb, yb in train_dl:
    print(xb)
    print(yb)

tensor([[69., 96., 70.],
        [69., 96., 70.],
        [91., 88., 64.],
        [73., 67., 43.],
        [91., 88., 64.]])
tensor([[103., 119.],
        [103., 119.],
        [ 81., 101.],
        [ 56.,  70.],
        [ 81., 101.]])
tensor([[ 87., 134.,  58.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [ 87., 134.,  58.]])
tensor([[119., 133.],
        [119., 133.],
        [ 22.,  37.],
        [ 56.,  70.],
        [119., 133.]])
tensor([[ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 81., 101.],
        [ 22.,  37.],
        [ 56.,  70.],
        [ 22.,  37.],
        [103., 119.]])


## nn.Linear

In [27]:
model = nn.Linear(in_features=3, out_features=2) #This has bias=True by default

In [28]:
print("Weights: ", model.weight)
print("Biases:", model.bias)

Weights:  Parameter containing:
tensor([[ 0.2187,  0.0082,  0.4136],
        [-0.5206, -0.4418, -0.3747]], requires_grad=True)
Biases: Parameter containing:
tensor([0.2325, 0.0422], requires_grad=True)


In [29]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.2187,  0.0082,  0.4136],
         [-0.5206, -0.4418, -0.3747]], requires_grad=True),
 Parameter containing:
 tensor([0.2325, 0.0422], requires_grad=True)]

In [30]:
preds = model(inputs)
print(preds)

tensor([[  34.5332,  -83.6737],
        [  47.3278, -110.1906],
        [  44.3477, -126.1839],
        [  38.1988,  -85.9190],
        [  45.0625, -104.5203],
        [  34.5332,  -83.6737],
        [  47.3278, -110.1906],
        [  44.3477, -126.1839],
        [  38.1988,  -85.9190],
        [  45.0625, -104.5203],
        [  34.5332,  -83.6737],
        [  47.3278, -110.1906],
        [  44.3477, -126.1839],
        [  38.1988,  -85.9190],
        [  45.0625, -104.5203]], grad_fn=<AddmmBackward>)


## Loss Function

In [31]:
import torch.nn.functional as F

In [32]:
loss_fn = F.mse_loss

In [33]:
loss = loss_fn(model(inputs), targets)

In [34]:
loss.item()

21125.052734375

In [35]:
print(loss)

tensor(21125.0527, grad_fn=<MseLossBackward>)


## Optimizer

In [36]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

## Train the model using following steps:
1. Generate predictions
2. Calculate Loss
3. Comptute grads w.r.t weights and biases
4. Adjust weights and biases
5. Reset gradients to zero

In [37]:
def fit(train_dl, model, loss_fn, optim, num_epochs):
    
    for epoch in range(num_epochs):
        
        #Train in batches of data
        for xb, yb in train_dl:
            
            # 1.Generate predictions
            preds = model(xb)
            
            # 2.Calculate loss
            loss = loss_fn(preds, yb)
            
            # 3.Compute grads. w.r.t weights and biases
            loss.backward()
            
            # 4.Update parameters
            opt.step()
            
            #5. Reset grads to zero
            
            opt.zero_grad()
            
        #Print progress
        if((epoch+1)%10==0):
            print("Epoch [{} / {}], Loss: {:.4f}".format(epoch+1, num_epochs, loss.item()))        

In [38]:
fit(train_dl, model, loss_fn, opt, 100)

Epoch [10 / 100], Loss: 378.7920
Epoch [20 / 100], Loss: 432.6642
Epoch [30 / 100], Loss: 297.9373
Epoch [40 / 100], Loss: 220.0924
Epoch [50 / 100], Loss: 136.6962
Epoch [60 / 100], Loss: 56.1517
Epoch [70 / 100], Loss: 64.8538
Epoch [80 / 100], Loss: 34.7764
Epoch [90 / 100], Loss: 51.8446
Epoch [100 / 100], Loss: 16.1510


In [39]:
preds = model(inputs)

In [40]:
print(preds, "\n", targets)

tensor([[ 58.4191,  71.5572],
        [ 82.6463,  97.8096],
        [115.5395, 137.3347],
        [ 28.2159,  43.9456],
        [ 98.5769, 110.1360],
        [ 58.4191,  71.5572],
        [ 82.6463,  97.8096],
        [115.5395, 137.3347],
        [ 28.2159,  43.9456],
        [ 98.5769, 110.1360],
        [ 58.4191,  71.5572],
        [ 82.6463,  97.8096],
        [115.5395, 137.3347],
        [ 28.2159,  43.9456],
        [ 98.5769, 110.1360]], grad_fn=<AddmmBackward>) 
 tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
